apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: practice-ingress
  annotations:
    cert-manager.io/cluster-issuer: le-staging
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: frontend
      port:
        name: frontendport
  rules:
  - host: k8spractice.homepluspower.info
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              name: backendport
  tls:
  - hosts:
    - k8spractice.homepluspower.info
    secretName: <TLS SECRET NAME>
